# Change these first
owner: clye-app # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Homepage
    url: https://clye.app
  - name: Bot
    url: https://bot.clye.app
  - name: LegalBFF
    url: https://legalbff.de

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Clye Uptime
  introTitle: "Hier ist die uptime un der aktuelle Status der CLYE Produkte zu sehen"
  introMessage: "Alle störungen sind hier aufgelistet"
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
